name: server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      run: |
        echo "${{ secrets.PAT_PACKAGES }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Docker build and push
      run: |
        TAG=ghcr.io/john2143/better_gha_runner:${{ github.run_number }}
        TAL=ghcr.io/john2143/better_gha_runner:latest

        docker build -t b . --label "runnumber=${{ github.run_number }}"
        docker tag b $TAG
        docker tag b $TAL
        docker push $TAG
        docker push $TAL

